import BasicLayout from "@/components/Layout";
import ExplorerPage from "@/container/Explorer";
import { getSession } from "next-auth/react";
import Head from "next/head";

export default function Explorer() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BasicLayout>
          <ExplorerPage />
        </BasicLayout>
      </main>
    </>
  );
}
// export async function getServerSideProps(context: any) {
//   const session = await getSession(context);

//   if (!session) {
//     return {
//       redirect: {
//         destination: "/signin",
//         permanent: false,
//       },
//     };
//   }

//   return {
//     props: { session },
//   };
// } 