import HomePage from "@/components/HomePage";
import BasicLayout from "@/components/Layout";
import { getSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mobigic front end</title>
        <meta name="description" content="Generated by Mobigic front end" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BasicLayout>
          <HomePage />
        </BasicLayout>
      </main>
    </>
  );
}
export async function getServerSideProps(context: any) {
  const session = await getSession(context);

  if (!session) {
    return {
      redirect: {
        destination: "/signin",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
